#!/usr/bin/env bash
# check.sh — the data-backed CI for frameprism.
#
# What this is: the single entrypoint that checks the repo against
# its own data — version pins (the byte-identity contracts), the
# committed-fixture provenance step (the 12 oracle source fixtures
# regenerated byte-identically by the committed deterministic
# generator, ci/fixture-templates/generate_fixtures.py — the
# fixtures' provenance authority),
# the release build + the suite gate (581/0/1), the clippy baseline
# gate (`cargo clippy --workspace -- -D warnings` — the [lints]-driven
# warning contract, the reason-documented allows pinned in tool's
# Cargo.toml [lints.clippy] — silent on PASS), the README command-list
# drift gate (the marker-delimited Commands block byte-diffed against
# the built binary's `--help` — silent on PASS), the 10-frame synthetic
# byte-identity oracle (67,762,584 B) from the COMMITTED fixture in
# ci/oracle10/, the 10/8-bit JXL oracle (2,380,943 B, the two synthetic
# committed 10/8-bit source frames, via check-108.sh), the JXL independent-decoder
# cross-check (the oracle108 gold decoded with jxl-oxide 0.12.6 — a
# SEPARATE implementation from the pinned libjxl cjxl/djxl pair —
# vs the source-derived planes, via check-xcheck.sh), the OFFLINE dependency audit
# (pinned cargo-audit v0.22.2 + pinned rustsec/advisory-db snapshot,
# via check-audit.sh), and the
# C-boundary fuzz corpus (25 pinned-outcome fixtures over `frameprism
# decode`, via check-fuzz.sh). Any failure is a named FAIL +
# rc=1 — no silent skips anywhere (the rule as an exit
# contract).
#
# CI note: this script IS the CI job: one GitHub Actions job running
# `bash ci/check.sh`, with rust. SELF-CONTAINED — the patched turbojpeg
# prefix (deps/.jpeg-prefix/{lib,include}) is COMMITTED with the repo
# (the byte-contract build input; no prefix setup step on the runner)
# + the pinned cjxl/djxl + the pinned cargo-audit binary + the pinned
# advisory-db (deps/pinned-binaries/ + deps/rustsec-advisory-db/ —
# COMMITTED with the repo, so the pins are self-contained; no libjxl /
# audit setup step needed on the runner); no Homebrew install on the
# runner (the in-process container components zstd/tar + the ISO
# writer fstool ride the committed Cargo.lock; python3 is the
# runner-preinstalled stdlib-only interpreter).
#
# Pin-drift note: a version drift (cjxl, zstd, tar, the
# tool itself) would SILENTLY change archive bytes — the byte
# claims are pinned to the exact versions in ci/pins.tsv; the pins
# are the contract.
#
# Suite-pin scope note: the suite pin is scoped to `--lib` (the
# shipped lib tests). An ALL-targets `cargo test --release`
# additionally runs the `vdct_probe` research-probe bin's 15 tests,
# which fail in this environment (fs::read NotFound — the DCT
# research TIFF fixtures are not committed; research probes are not
# shipped features) — expected + by design, not a regression
# (the lib-test gate). The gate runs `--lib`.
#
# CLI: check.sh [--repo <path>] [--oracle-src <dir>]
#   --repo        repo root (default: this script's grandparent)
#   --oracle-src  oracle source dir (default: ci/oracle10/src under
#                 the repo — the committed fixture)
# Env:  JPEG_TURBO_PREFIX (default <repo>/deps/.jpeg-prefix),
#       CARGO_TARGET_DIR (default <repo>/target), CI_CJXL_BIN /
#       CI_DJXL_BIN (pin overrides), CI_CARGO_AUDIT_BIN (the audit
#       binary pin override).
# Exit: 0 ALL PASS, 1 any named FAIL.

set -u

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="$(cd "$SCRIPT_DIR/.." && pwd)"
ORACLE_SRC=""

while [ $# -gt 0 ]; do
  case "$1" in
    --repo) REPO="$2"; shift 2 ;;
    --oracle-src) ORACLE_SRC="$2"; shift 2 ;;
    *) echo "check: unknown argument: $1" >&2; exit 2 ;;
  esac
done
[ -n "$ORACLE_SRC" ] || ORACLE_SRC="$SCRIPT_DIR/oracle10/src"

export JPEG_TURBO_PREFIX="${JPEG_TURBO_PREFIX:-$REPO/deps/.jpeg-prefix}"
export CARGO_TARGET_DIR="${CARGO_TARGET_DIR:-$REPO/target}"

echo "=== ci check: $(date '+%Y-%m-%d %H:%M:%S') repo=$REPO ==="

# --- step 1: version pins ---------------------------------------------------
PINS_OUT="$(bash "$SCRIPT_DIR/check-pins.sh" --repo "$REPO" 2>&1)"
pins_rc=$?
echo "$PINS_OUT"
if [ $pins_rc -ne 0 ]; then
  echo "FAIL ci check: pins step rc=$pins_rc (named PIN FAILs above)"
  exit 1
fi
PINS_OK="$(printf '%s\n' "$PINS_OUT" | sed -n 's/^pins: \([0-9]*\)\/.*/\1/p' | tail -1)"
PINS_TOT="$(printf '%s\n' "$PINS_OUT" | sed -n 's/^pins: [0-9]*\/\([0-9]*\) OK.*/\1/p' | tail -1)"

# --- step 2: fixture provenance (the committed fixtures' authority) ----
# The 12 committed oracle source fixtures (ci/oracle10/src/ +
# ci/oracle108/src/) are deterministic synthetic CFA content in
# sanitized Sigma fp container templates: the committed generator
# (ci/fixture-templates/generate_fixtures.py, python3 stdlib only)
# authenticates every fixture against the committed sha256 manifest
# (ci/fixture-templates/fixture-manifest.sha256), regenerates all 12
# from the tree's own committed templates (the self-template mode),
# and byte-compares each against the committed file. Read-only against
# the tree (the temp dir is removed on every path); ~60 s on the
# reference machine. python3 missing = a named FAIL (the pins step's
# python3 row says the same at the pins surface); any mismatch or
# structural failure = the generator's named FAIL naming the
# offending path (rc != 0) + the gate's named FAIL — no silent skip.
if ! python3 "$SCRIPT_DIR/fixture-templates/generate_fixtures.py" --verify --repo "$REPO"; then
  echo "FAIL ci check: the fixture-provenance step failed (the generator's named FAIL above — a committed fixture does not regenerate byte-identically, or python3 is missing)"
  exit 1
fi

# --- step 3: release build + suite gate -------------------------------------
echo "--- build (release) ---"
if ! (cd "$REPO/tool" && cargo build --release); then
  echo "FAIL ci check: cargo build --release failed"
  exit 1
fi
echo "--- suite (cargo test --release --lib) ---"
SUITE_LOG="$(cd "$REPO/tool" && cargo test --release --lib 2>&1)"
SUITE_LINE="$(printf '%s\n' "$SUITE_LOG" | grep 'test result' | tail -1)"
case "$SUITE_LINE" in
  ""*"581 passed; 0 failed; 1 ignored"*)
    echo "$SUITE_LINE" ;;
  *)
    echo "FAIL ci check: suite gate drift — expected '581 passed; 0 failed; 1 ignored', got: ${SUITE_LINE:-'(no test result line — build/test error, log tail below)'}"
    printf '%s\n' "$SUITE_LOG" | tail -5
    exit 1 ;;
esac

# --- step 4: clippy baseline gate (the [lints]-driven warning contract) --
# The tool's lint baseline: `cargo clippy --workspace` (the
# DEV-profile pass, the default targets — lib + bins) with -D warnings,
# driven by the [lints.clippy] table in tool/Cargo.toml (the table pins
# the allowed subset + the reason-documented allows; whatever else
# warns fails here — a new warning class = the named FAIL until fixed
# or pinned with a reason). Silent on PASS (no summary token — the 50
# precedent, the summary line is unchanged); a warning = the named FAIL
# + the clippy output tail.
CLIPPY_LOG="$(cd "$REPO/tool" && cargo clippy --workspace -- -D warnings 2>&1)"
clippy_rc=$?
if [ $clippy_rc -ne 0 ]; then
  echo 'FAIL ci check: the clippy baseline gate — the [lints]-driven clippy run carries warnings (fix the warning or pin the reason-documented allow in tool/Cargo.toml'"'"'s [lints.clippy])'
  printf '%s\n' "$CLIPPY_LOG" | tail -30
  exit 1
fi

# --- step 5: README command-list drift gate (the verbatim block) ----------
# The README's marker-delimited Commands block (between the pinned
# `frameprism-help-commands:begin` / `:end` comments) must be
# byte-identical to the built binary's `frameprism --help` Commands
# section (the lines from `Commands:` to the first blank line after
# it). Silent on PASS (no summary token — the summary line is
# unchanged); a drift = the named FAIL + the diff. Regenerate the
# block from the built binary — do not edit it by hand.
BIN="$CARGO_TARGET_DIR/release/frameprism"
WANT_CMDS="$(printf '%s\n' "$("$BIN" --help)" | awk '/^Commands:$/{f=1} f&&/^[[:space:]]*$/{exit} f{print}')"
HAVE_CMDS="$(awk '/frameprism-help-commands:begin/{f=1;next} /frameprism-help-commands:end/{f=0} f' "$REPO/README.md" | awk '!/^```$/{print}')"
if [ -z "$WANT_CMDS" ] || [ -z "$HAVE_CMDS" ]; then
  echo 'FAIL ci check: the README command-list drift gate — could not extract the binary'"'"'s --help Commands section or the README'"'"'s marker block (the markers missing?)'
  exit 1
fi
if [ "$WANT_CMDS" != "$HAVE_CMDS" ]; then
  echo 'FAIL ci check: the README command-list drift gate — the README'"'"'s Commands block is not byte-identical to the binary'"'"'s `frameprism --help` Commands section (regenerate the block between the pinned markers from the built binary)'
  diff <(printf '%s\n' "$WANT_CMDS") <(printf '%s\n' "$HAVE_CMDS") || true
  exit 1
fi

# --- step 6: 10f oracle (byte-identity, the committed fixture) --------------
BIN="$CARGO_TARGET_DIR/release/frameprism"
GOLD="$SCRIPT_DIR/oracle10/gold"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
echo "--- oracle10 (encode $ORACLE_SRC → byte-identity vs $GOLD) ---"
"$BIN" "$ORACLE_SRC" "$TMP/out" --jobs 1 > "$TMP/oracle-run.log" 2>&1
enc_rc=$?
if [ $enc_rc -ne 0 ]; then
  # (rc captured before the test — `$?` inside `if ! cmd` is the NEGATED
  # status; the first version of this branch printed the wrong rc)
  echo "FAIL ci check: oracle encode failed (rc=$enc_rc, log tail below)"
  tail -5 "$TMP/oracle-run.log"
  exit 1
fi
ident=0; miss=0; tot=0
for f in "$GOLD"/*.DNG; do
  b="$(basename "$f")"
  if [ ! -f "$TMP/out/$b" ]; then
    echo "FAIL ci check: oracle output missing: $b"
    miss=$((miss+1)); continue
  fi
  if cmp -s "$f" "$TMP/out/$b"; then
    ident=$((ident+1))
  else
    echo "FAIL ci check: oracle mismatch: $b"
    miss=$((miss+1))
  fi
  s=$(stat -f%z "$TMP/out/$b"); tot=$((tot+s))
done
if [ "$ident" -ne 10 ] || [ "$miss" -ne 0 ] || [ "$tot" -ne 67762584 ]; then
  echo "FAIL ci check: oracle $ident/10 identical, total $tot (expected 10/10, 67762584 B)"
  exit 1
fi
echo "oracle: $ident/10 byte-identical, total $tot B (oracle 67762584)"

# --- step 7: 10/8-bit JXL oracle (byte-identity, the committed fixture) ----
# check-108.sh re-asserts the cjxl/djxl pin + the release build (no-op)
# internally; its EXPECTED_TOTAL (2,380,943 B) is the byte-identity
# contract for the 10/8-bit JXL bytes.
if ! bash "$SCRIPT_DIR/check-108.sh" --repo "$REPO"; then
  echo "FAIL ci check: check-108.sh (oracle108) failed"
  exit 1
fi

# --- step 8: JXL independent-decoder cross-check -------------------------
# check-xcheck.sh builds the harness (ci/jxl-xcheck/ — a separate
# crate; the tool's dep tree + audit baseline are untouched) and runs
# it: the 8 oracle108 gold planes decoded with jxl-oxide 0.12.6 (a
# separate implementation from the pinned libjxl cjxl/djxl pair the
# --verify round-trip uses) must be byte-exact against the
# source-derived planes (the j92 round-trip; no libjxl anywhere).
if ! bash "$SCRIPT_DIR/check-xcheck.sh" --repo "$REPO"; then
  echo "FAIL ci check: check-xcheck.sh (the JXL independent-decoder cross-check) failed"
  exit 1
fi

# --- step 9: dependency audit (offline, pinned cargo-audit + pinned db) ---
if ! bash "$SCRIPT_DIR/check-audit.sh" --repo "$REPO"; then
  echo "FAIL ci check: check-audit.sh (dependency audit) failed"
  exit 1
fi

# --- step 10: C-boundary fuzz corpus (pinned outcomes) -----------------------
if ! bash "$SCRIPT_DIR/check-fuzz.sh" --repo "$REPO"; then
  echo "FAIL ci check: check-fuzz.sh (fuzz corpus) failed"
  exit 1
fi

# --- step 11: summary ---------------------------------------------------------
echo "ci check: ALL PASS (pins $PINS_OK/$PINS_TOT, fixtures 12/12 regenerated, suite 581/0/1, oracle10 10/10 @ 67762584 B, oracle108 10/10 @ 2380943 B, audit 0 vulns (124 deps), fuzz 25/25 pinned)"
exit 0
